FROM dwp-centos-with-java:latest

EXPOSE 8080
EXPOSE 8443

RUN mkdir -p /opt/data-key-service/data
WORKDIR /opt/data-key-service

RUN wget $(curl --silent --insecure "https://api.github.com/repos/dwp/data-key-service/releases/latest" \
    | jq -r '.assets[0].browser_download_url') --no-check-certificate --output-document dks-latest.jar

RUN ls -la *.jar

COPY application-dks-secure.properties ./
COPY certs/dks/* ./

ENTRYPOINT ["sh", "-c", "java -jar dks-latest.jar \"$@\"", "--"]
