FROM dwp-pthon-preinstall:latest

COPY populator/requirements.txt populator/*.py populator/*.json ./
RUN pip3 install --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -r ./requirements.txt

RUN chown -R ${SERVICE_USER}.${SERVICE_USER} ${SERVICE_USER_HOME}
RUN chown -R ${SERVICE_USER}.${SERVICE_USER} ${INSTALL_DIR}
USER $SERVICE_USER
ENTRYPOINT ["./populate_hbase.py"]
