FROM python:3.7-slim

RUN mkdir -p /opt/test /data/output
WORKDIR /opt/test

COPY integration_test.py ./

RUN ls ./
RUN which python3
RUN echo $PATH
ENTRYPOINT ["sh", "-c", "python integration_test.py \"$@\"", "--"]
