FROM python:3.7.3-stretch

ENV SERVICE_USER=dataworks
ENV SERVICE_USER_HOME=/home/${SERVICE_USER}
ENV INSTALL_DIR=/opt/hbase-to-mongo-export
RUN mkdir -p ${SERVICE_USER_HOME} ${INSTALL_DIR}/data /opt/snapshot-sender/data
RUN useradd -d ${SERVICE_USER_HOME} ${SERVICE_USER}
RUN id -a ${SERVICE_USER}

WORKDIR $INSTALL_DIR
COPY populator/requirements.txt ./
RUN pip3 install --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -r ./requirements.txt
COPY populator/*.py populator/*.json ./
RUN chown -R ${SERVICE_USER}.${SERVICE_USER} ${SERVICE_USER_HOME}
RUN chown -R ${SERVICE_USER}.${SERVICE_USER} ${INSTALL_DIR} /opt/snapshot-sender/data
RUN ls -l /opt/snapshot-sender/data
USER $SERVICE_USER
ENTRYPOINT ["./populate_hbase.py"]
