FROM dwp-centos-with-java:latest

RUN mkdir -p /opt/hbase-to-mongo-export/data /opt/snapshot-sender/data
WORKDIR /opt/hbase-to-mongo-export

RUN wget $(curl --silent --insecure "https://api.github.com/repos/dwp/hbase-to-mongo-export/releases/latest" \
    | jq -r '.assets[0].browser_download_url') --no-check-certificate --output-document htme-latest.jar


COPY htme*.jks htme*.crt ./
COPY htme.properties ./application.properties
RUN chmod a+rwx -R /opt/hbase-to-mongo-export/ /opt/snapshot-sender/

ENTRYPOINT ["sh", "-c", "java -Dtopic.name=test -jar htme-latest.jar \"$@\"", "--"]

