FROM centos:latest

RUN echo hello
RUN mkdir -p /opt/snapshot-sender/data

RUN yum -y upgrade
RUN yum install -y epel-release
RUN yum install -y java-1.8.0-openjdk wget jq
ENV JAVA_HOME /etc/alternatives/jre

RUN chmod a+rwx -R /opt/snapshot-sender/ /opt/snapshot-sender/data
