FROM dwp-centos-with-java:latest
ENV SPRING_CONFIG_LOCATION /opt/mock-nifi/application-mock-nifi.properties

EXPOSE 5443

RUN mkdir -p /opt/mock-nifi/data /opt/snapshot-sender/data
WORKDIR /opt/mock-nifi

RUN wget $(curl --silent --insecure "https://api.github.com/repos/dwp/mock-nifi/releases/latest" \
    | jq -r '.assets[0].browser_download_url') --quiet --no-check-certificate --output-document mock-nifi-latest.jar

RUN ls -la *.jar

COPY application-mock-nifi.properties ./
COPY mock-nifi*.jks ./

ENTRYPOINT ["sh", "-c", "java -jar mock-nifi-latest.jar \"$@\"", "--"]
