FROM centos

RUN mkdir /opt/data-key-service

RUN yum -y upgrade
RUN yum install -y epel-release
RUN yum install -y java-1.8.0-openjdk wget jq
ENV JAVA_HOME /etc/alternatives/jre
ENV SPRING_CONFIG_LOCATION application-htme.properties

WORKDIR /opt/hbase-to-mongo-export

RUN wget $(curl --silent --insecure "https://api.github.com/repos/dwp/hbase-to-mongo-export/releases/latest" \
    | jq -r '.assets[0].browser_download_url') --no-check-certificate --output-document htme-latest.jar

RUN ls -la *.jar

COPY application-htme.properties ./
COPY certs/htme/* ./

ENTRYPOINT ["sh", "-c", "java -jar htme-latest.jar \"$@\"", "--"]