FROM python:3.7-slim

RUN apt-get update && apt-get install -y gcc python3-dev

RUN mkdir /ssl /data

WORKDIR /app

COPY mock-nifi/requirements.txt .

RUN pip3 install -r requirements.txt

COPY mock-nifi/* ./

CMD ["python3", "mocknifi.py"]
