name: Build and test

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [get-publish-version]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          java-package: jdk
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 5.5.1

      - name: Build
        run: |
          set -u
          set +o pipefail
          LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          set -o pipefail
          [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
          VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          VERSION_NUMBER=$(echo $VERSION | sed 's/^v\(.*\)$/\1/')
          sed -i -e "s/version = \"0.0.0\"/version = \"$VERSION\"/" build.gradle.kts

          mkdir artifacts
          gradle build --stacktrace
          cp build/libs/snapshot-sender-*.jar ./artifacts/

      - name: Integration Test
        run: |
          sudo pip3 install docker-compose
          sudo apt-get update
          sudo apt-get install make

          cd resources
          ./generate-developer-certs.sh
          cd -

          make jar
          docker-compose build
          make up
          make integration-tests


