name: Build and test

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          java-package: jdk
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: |
          mkdir artifacts
          gradle build --stacktrace
          cp build/libs/snapshot-sender-*.jar ./artifacts/

      - name: Integration Test
        run: |
          sudo pip3 install docker-compose
          sudo apt-get update
          sudo apt-get install make

          cd resources
          ./generate-developer-certs.sh
          cd -

          make jar
          docker-compose build
          make up
          make integration-tests


